### ISSUE TITLE
The protocol should be described in the wiki

### ISSUE THREAD

**Issue by DanielSank** [labrad/labrad#11]
Linking to Markus's thesis is kinda janky.

**Comment by maffoo** [comment]
Documented the encoding and rpc protocols in the wiki: https://github.com/labrad/labrad/wiki/LabRAD-specification. The link to Markus's thesis is still there, but not as prominently placed and hopefully can be removed soon. Take a look, and let me know if there are any big gaps you'd like to see filled in the docs.

**Comment by DanielSank** [comment]
This looks great. Thanks much, Bumblebee.
