### ISSUE TITLE
Would-be users are put off because they can't easily get a manager binary

### ISSUE THREAD

**Issue by DanielSank** [labrad/labrad#6]
I think this means I need to stop finding excuses not to test @maffoo's new Scala implementation.

**Comment by DanielSank** [comment]
bump @maffoo. The scalabrad readme doesn't give any hints about this. That might be a simple fix to this issue.

**Comment by maffoo** [comment]
Added a note in the scalabrad README about where to download binaries and how to run them.

**Comment by DanielSank** [comment]
Thanks, this will help very much.
