### ISSUE TITLE
How do messages work?

### ISSUE THREAD

**Issue by joshmutus** [labrad/labrad#7]
How do I make a thing that works with LabRAD messages?

**Comment by DanielSank** [comment]
@maffoo it would be nice to have a wiki page on this. I don't actually know how messages work. Is this only documented in Markus's thesis?

**Comment by DanielSank** [comment]
@joshmutus if you eventually got the answer to your question, could you make a wiki page and then close this afterwards?

**Comment by DanielSank** [comment]
bump

**Comment by maffoo** [comment]
I started documenting messages in general here: https://github.com/labrad/labrad/wiki/RPC-Protocol. Will add more about doing this in pylabrad/scalabrad on their respective wikis.

**Comment by joshm-3b6b58** [comment]
Thanks, sorry I haven't replied, but I haven't heard from anybody about
messages. Thanks for starting the documentation.

**Comment by maffoo** [comment]
closing for now; we can file issues for specific language APIs if needed.
