### ISSUE TITLE
Support integers with units

### ISSUE THREAD

**Issue by DanielSank** [labrad/labrad#8]
The labrad implementation could have these rules:

1. Type tag would be e.g. `i[Hz]`.

1. A setting advertising `i[Hz]` accepts `i[kHz]`.

1. A setting advertising `i[Hz]` does not accept `i[mHz]`.

1. A setting advertising `v[Hz]` accepts `i[Hz]`.

1. A setting advertising `i[Hz]` does not accept `v[Hz]`.

1. Advertising both `v[Hz]` and `i[Hz]` makes you a bad person.

To illustrate the idea, I give an example of how the pylabrad in-memory implementation could work:
```python
>>> x = IntValue(5, 'us')
>>> x['ns']
5000
>>> type(x['ns'])
int
>>> x['ms']
ValueError: Converting from 'us' to 'ms' requires non-integer numbers.
>>> x.in_units('ms', float_ok=True)
0.001
```

~~@maffoo @ejeffrey @pomalley pinging you guys in case you aren't watching this repo.~~
I think the fact that it let me ping you means you are watching the repo :-P

**Comment by ejeffrey** [comment]
I don't really like the idea of integers with units.

**Comment by DanielSank** [comment]
I remember your prior objection to this based on the impossibility of accessing an e.g. `i[mHz]` in units of `Hz`, but the proposed system doesn't allow that. Is there some other problem or is it just that the proposed feature doesn't seem useful?

**Comment by ejeffrey** [comment]
It seems to me that by adding the restrictions that you can't convert to
larger units you severely limit the value of the unit attribute. You also
have to deal with arithmetic issues: do you follow the promotion rules of c
or python or do you force people to exploring l explicitly cast to float
when needed. Finally it is seems in principle wrong. If you need an integer
you aren't really measuring something in physical units. For instance:
delays in FPGA code are not really integer nanoseconds, they are integer
clock cycles and the clock happens to be 1 GHz. If the DAC clock were 1.2
GHz then your proposal wouldn't help.

**Comment by DanielSank** [comment]
These are all good points. Of course, the real issue here is how to deal with setting physical values on digital equipment. For example, how should we set an RF source frequency? Should we change all the setting names to things like `set_frequency_Hz`? Should we round the user's input `v[Hz]` and return them the value actually set? Can we trust people to act on that return value in any way?

**Comment by ejeffrey** [comment]
I think we round the users v[Hz] and return the actual value and expect the
user to use that as needed.  If necessary, add specific alternate methods
such as get_freq_resolution(v[Hz]) and set_freq_counts(i) or
set_freq_machine_units(p, q) (set to rational frequency p/q) that support
setting exact hardware values when necessary.  I wouldn't call them
set_freq_Hz or anything like that ties it to SI units: the point is that
you are using the machine units (whatever they are) and forcing the user to
manually account for the physical units.

**Comment by DanielSank** [comment]
I think #10 encapsulates the issue raised here, so closing this and linking this in #10 so the discussion isn't lost.
